create table if not exists questions (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('literasi','numerasi')),
  difficulty text not null check (difficulty in ('easy','medium','hard')),
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer text not null check (correct_answer in ('A','B','C','D')),
  created_at timestamptz default now()
);

create table if not exists battles (
  id bigint generated by default as identity primary key,
  category text not null,
  difficulty text not null,
  team_a_name text not null,
  team_b_name text not null,
  team_a_score integer default 0,
  team_b_score integer default 0,
  winner text,
  created_at timestamptz default now()
);

create table if not exists team_members (
  id bigint generated by default as identity primary key,
  battle_id bigint references battles(id) on delete cascade,
  team text not null check (team in ('A','B')),
  name text not null
);

create table if not exists battle_questions (
  id bigint generated by default as identity primary key,
  battle_id bigint references battles(id) on delete cascade,
  question_id bigint references questions(id),
  team text not null check (team in ('A','B')),
  round integer not null,
  answer text,
  is_correct boolean
);

create table if not exists penalties (
  id bigint generated by default as identity primary key,
  penalty text not null,
  created_at timestamptz default now()
);

-- Development-only policies. Tighten these before production.
alter table questions enable row level security;
alter table battles enable row level security;
alter table team_members enable row level security;
alter table battle_questions enable row level security;
alter table penalties enable row level security;

create policy "public read questions" on questions for select using (true);
create policy "public read penalties" on penalties for select using (true);