-- BattleCraft database schema for Supabase.
-- Run this entire file once in Supabase Dashboard > SQL Editor.
-- The policies at the bottom are intentionally open for the current demo app,
-- which uses a client-side demo login instead of Supabase Auth.

create extension if not exists pgcrypto;

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('literasi', 'numerasi')),
  difficulty text not null default 'medium' check (difficulty in ('easy', 'medium', 'hard')),
  question text not null check (length(trim(question)) > 0),
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer text not null check (correct_answer in ('A', 'B', 'C', 'D')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.battles (
  id uuid primary key default gen_random_uuid(),
  category text not null check (category in ('literasi', 'numerasi')),
  difficulty text not null default 'medium' check (difficulty in ('easy', 'medium', 'hard')),
  team_a_name text not null check (length(trim(team_a_name)) > 0),
  team_b_name text not null check (length(trim(team_b_name)) > 0),
  team_a_score integer not null default 0 check (team_a_score >= 0),
  team_b_score integer not null default 0 check (team_b_score >= 0),
  winner text check (winner in ('A', 'B', 'DRAW') or winner is null),
  status text not null default 'started' check (status in ('started', 'finished', 'cancelled')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  battle_id uuid not null references public.battles(id) on delete cascade,
  team text not null check (team in ('A', 'B')),
  name text not null check (length(trim(name)) > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.battle_questions (
  id bigint generated by default as identity primary key,
  battle_id uuid not null references public.battles(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  team text not null check (team in ('A', 'B')),
  round integer not null check (round between 1 and 25),
  answer text check (answer in ('A', 'B', 'C', 'D') or answer is null),
  is_correct boolean,
  answered_at timestamptz,
  created_at timestamptz not null default now(),
  unique (battle_id, team, round)
);

create table if not exists public.penalties (
  id bigint generated by default as identity primary key,
  penalty text not null unique check (length(trim(penalty)) > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Compatibility migration for databases created from the first schema version.
-- CREATE TABLE IF NOT EXISTS does not add columns to an existing table.
alter table public.questions add column if not exists difficulty text;
alter table public.questions add column if not exists is_active boolean;
alter table public.questions add column if not exists updated_at timestamptz;

update public.questions set difficulty = 'medium' where difficulty is null;
update public.questions set is_active = true where is_active is null;
update public.questions set updated_at = coalesce(created_at, now()) where updated_at is null;

alter table public.questions alter column difficulty set default 'medium';
alter table public.questions alter column difficulty set not null;
alter table public.questions alter column is_active set default true;
alter table public.questions alter column is_active set not null;
alter table public.questions alter column updated_at set default now();
alter table public.questions alter column updated_at set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'questions_difficulty_check'
      and conrelid = 'public.questions'::regclass
  ) then
    alter table public.questions
      add constraint questions_difficulty_check
      check (difficulty in ('easy', 'medium', 'hard'));
  end if;
end;
$$;

create index if not exists questions_category_active_idx
  on public.questions (category, is_active);
create index if not exists questions_difficulty_idx
  on public.questions (difficulty);
create index if not exists battles_created_at_idx
  on public.battles (created_at desc);
create index if not exists team_members_battle_idx
  on public.team_members (battle_id, team);
create index if not exists battle_questions_battle_idx
  on public.battle_questions (battle_id, round);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists questions_set_updated_at on public.questions;
create trigger questions_set_updated_at
before update on public.questions
for each row execute function public.set_updated_at();

drop trigger if exists battles_set_updated_at on public.battles;
create trigger battles_set_updated_at
before update on public.battles
for each row execute function public.set_updated_at();

drop trigger if exists penalties_set_updated_at on public.penalties;
create trigger penalties_set_updated_at
before update on public.penalties
for each row execute function public.set_updated_at();

alter table public.questions enable row level security;
alter table public.battles enable row level security;
alter table public.team_members enable row level security;
alter table public.battle_questions enable row level security;
alter table public.penalties enable row level security;

-- Remove old policies so this file can be safely re-run.
drop policy if exists "questions public access" on public.questions;
drop policy if exists "battles public access" on public.battles;
drop policy if exists "team members public access" on public.team_members;
drop policy if exists "battle questions public access" on public.battle_questions;
drop policy if exists "penalties public access" on public.penalties;

-- Development policies for the current client-side demo application.
create policy "questions public access" on public.questions
for all to anon, authenticated using (true) with check (true);

create policy "battles public access" on public.battles
for all to anon, authenticated using (true) with check (true);

create policy "team members public access" on public.team_members
for all to anon, authenticated using (true) with check (true);

create policy "battle questions public access" on public.battle_questions
for all to anon, authenticated using (true) with check (true);

create policy "penalties public access" on public.penalties
for all to anon, authenticated using (true) with check (true);

insert into public.penalties (penalty)
values
  ('Nyanyi 1 lagu anak-anak atau lagu pop'),
  ('Joget gaya karakter Minecraft selama 15 detik'),
  ('Tirukan suara hewan peliharaan'),
  ('Berikan tepuk tangan hebat untuk tim pemenang'),
  ('Lari di tempat sambil meneriakkan BattleCraft 10 kali'),
  ('Berpose menjadi patung batu selama 20 detik'),
  ('Bacakan pantun lucu buatan sendiri'),
  ('Tirukan gaya dinosaurus atau Creeper berjalan')
on conflict (penalty) do nothing;